- name: Capabilities and icecast2 package
  become: true
  apt:
    state: latest
    name:
      - libcap2-bin
  when: icecast_use_capabilities
- name: enable deb-src on debian
  apt_repository:
    repo: "deb-src http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib non-free"
    state: "{{ ( icecast_install_method == 'source' ) | ternary('present', 'absent') }}"
    filename: src
- name: Packages required for compilation
  become: true
  apt:
    state: build-dep
    name: icecast2
  when: icecast_install_method == 'source'
- name: Other dependencies
  package:
    name:
      - libssl-dev
      - git
  when: icecast_install_method == 'source'
